#!/bin/bash
PLAYLIST="$(mpc lsplaylists | rofi -lines 10 -dmenu -p 'Play MPD Playlist: ')"
if [ "$PLAYLIST" = "" ]; then
	exit
fi
mpc clear
mpc load $PLAYLIST
mpc play
notify-send -u low -t 5 -a 'Mopidy' "$PLAYLIST" "Beginning playback of playlist $PLAYLIST"
