#!/bin/bash

# Copyright (c) 2017 rehashedsalt/vintagesalt
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

## Patch path, if not already done
if [[ "$PATH" != "*$HOME/.local/bin" ]]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

## bspwm GENERAL CONFIGURATION
hostname=$(hostname)
hosts_single=(iridium)
for host in $hosts_single; do
	if [ $hostname = $host ]; then
		bspc monitor -d 1 2 3 4 5 6 7 8
	fi
done
if [ $hostname = tungsten ]; then
	$HOME/.local/bin/layout/tungsten.sh
	bspc monitor -o DisplayPort-0 HDMI-0
	bspc monitor DisplayPort-0 -d 1 2 3 4
	bspc monitor HDMI-0 -d 5 6 7 8
fi

bspc config border_width	4
bspc config window_gap		10

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc focus_follows_pointer	true
bspc click_to_focus		true

bspc pointer_follows_focus	true
bspc pointer_follows_monitor	true
bspc pointer_modifier		mod1
bspc pointer_action1		move
bspc pointer_action2		resize_corner

bspc config normal_border_color			"#eee8d5"
bspc config active_border_color			"#268bd2"
bspc config focused_border_color		"#657b83"
bspc config presel_border_color			"#6c71c4"
bspc config urgent_border_color			"#b58900"

## bspwm WINDOW RULES
bspc rule -a Waterfox desktop=1
bspc rule -a Spotify desktop=10

## SIMPLE CONFIGURATION
xset -b
xset -dpms
xset s off

## SERVICES AND DAEMONS
sxhkd &						# Simple hotkey daemon
feh --randomize --bg-fill ~/Pictures/Wallpapers/i3 &
if [[ $(pgrep polybar) ]]; then
	# Just covering bases here. Makes it easy to reload settings.
	killall polybar
fi
$HOME/.config/polybar/start.sh &

if [[ $(pgrep conky) ]]; then
	killall conky
fi
conky &
