#!/bin/bash

# Copyright (c) 2017 rehashedsalt/vintagesalt
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

## PATCH PATH, IF NOT ALREADY DONE
if [[ "$PATH" != "*$HOME/.local/bin" ]]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

## SIMPLE CONFIGURATION
xset -b
xset -dpms
xset s off

## SERVICES AND DAEMONS
sxhkd &						# Simple hotkey daemon
feh --randomize --bg-fill ~/Pictures/Wallpapers/i3 &
polybar alpha & 				# Simple bar

## bspwm GENERAL CONFIGURATION
bspc monitor -d			1 2 3 4 5 6 7 8 9 10

bspc config border_width	2
bspc config window_gap		4

bspc config split_ratio		0.52
bspc config borderless_monocle	true
bspc config gapless_monocle	true
bspc focus_follows_pointer	true
bspc pointer_follows_focus	true
bspc pointer_follows_monitor	true

bspc config normal_border_color			"#1d2021"
bspc config active_border_color			"#83a598"
bspc config focused_border_color		"#458588"
bspc config presel_border_color			"#d3869b"
bspc config urgent_border_color			"#fabd2f"

## bspwm WINDOW RULES
bspc rule -a Waterfox desktop=I
bspc rule -a Spotify desktop=X

